### ISSUE TITLE
Only female models are available

### ISSUE THREAD

**Issue by BrawnyAi** [frankchieng/ComfyUI_MagicClothing#15]
I'm trying to add a man in business suit to a male model but it all comes female ones for "magic_clothing_768_....safetensors" model. Is that normal?

**Comment by BrawnyAi** [comment]
ok, i had to tweak the prompt, it seems to show up now. lol thanks for the work!

**Comment by xpluscal** [comment]
@BrawnyAi how did you tweak your prompt? Having the same issue even if adding "1man" or "male" or so to prompt

**Comment by BrawnyAi** [comment]
You can try doing something like this, since this is a sd 1.5;

"(A man:1.8) dressing a shirt." Just adjust the weight until the man shows up.
